module.exports = {
    mongoURI: process.env.MONGO_URI,
    logLevel: "debug",
    docspringId: process.env.DOCSPRING_ID,
    docspringSecret: process.env.DOCSPRING_SECRET,
    pier_admin_key: process.env.PIER_ADMIN_KEY,
    docspringTest: true,
    allow_sandbox_testing_endpoints: true,
    envo: "default",
    logLevel: "debug",
    nls_username: process.env.NLS_USERNAME,
    nls_password: process.env.NLS_PASSWORD,
    nls_client_id: process.env.NLS_CLIENT_ID,
    nls_secret: process.env.NLS_SECRET,
    nls_scope: process.env.NLS_SCOPE,
    slack_bot_id: process.env.SLACK_BOT_ID,
    aes_secret_key: process.env.AES_SECRET_KEY,
    aes_iv: process.env.AES_IV,
    current_date: "06/21/2023" // for testing only
}
